### ISSUE TITLE
Strange behaviour of orderings for big spatial fields

### ISSUE THREAD

**Issue by acallesalda** [katzfuss-group/veccs#4]
I encountered a bug some days ago trying to run the ordering for some locations of a spatial field of size (64 x 64), that is, a locations matrix of size 4096x2. I uploaded the locations in the following file: [locs.csv](https://github.com/katzfuss-group/veccs/files/15080064/locs.csv)

This locations correspond to regular observations on the [0,1]^2, with 64 x 64 = 4096 observations each field, i.e., 

```import pandas as pd
import torch
import numpy as np
import veccs.orderings

locs_1 = pd.read_csv('../tests/data/locs.csv', header=None)
locs_1 = torch.from_numpy(locs_1.values)
locs_1 = locs_1.type(torch.float32)
locs_1.shape

torch.Size([4096, 2])
```

```
locs_1
tensor([[0.0000, 0.0000],
        [0.0000, 0.0159],
        [0.0000, 0.0317],
        ...,
        [1.0000, 0.9683],
        [1.0000, 0.9841],
        [1.0000, 1.0000]])
```

So, when I run the ordering, I expect 4096 different indexes for the order. But I get:

```
len(np.unique(order))
97
```

That is, we only got 97 different indexes for the ordering. If I for example print the last 100 indexes for the order,

```
order[-100:]
array([4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066,
       4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066,
       4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066,
       4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066,
       4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066,
       4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066,
       4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066,
       4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066,
       4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066, 4066,
       4066])
```

It turns out the last 4000 values of the ordering are just that single number repeated 4000 times. 

An even stranger thing I noticed trying to recreate the bug. Let's define the locations on the [0,1]^2 

```
import itertools

x = np.linspace(start=0.0, stop=1.0, num=64)
y = x
prod = itertools.product(x, y)
locs = torch.tensor(np.asarray(list(prod)), dtype=torch.float32)
torch.all(locs == locs_1)
tensor(True)

```

That is, I generated a new tensor of locations, `locs`, identical to `locs_1` which was a tensor of locations I read from a csv file. 

Running 

```
order = veccs.orderings.maxmin_cpp(locs)
len(np.unique(order))
4096
```

gives me the correct ordering. How is that possible? How can the same tensor of locations give out two different orderings (one correct, one wrong), given that one was generated by code and the other readen from a .csv file? Does this make sense? By the way, both tensors have the same type `torch.float32`.

**Comment by wiep** [comment]
not a fix, but helpful for now so that the bug is at least detected would be to check that the number unique elements in the returned vector is equal to the number of rows `locs`.

**Comment by wiep** [comment]
The issue observed is most likely due to using torch.tensor instead of numpy.ndarray. #5 adds runtime checks to the function `maxmin_cpp`.
